<#
.SYNOPSIS
    Converts a solid magenta/pink background (as generated by Generate-Image.ps1
    prompts asking for an isolated object on a magenta backdrop) into real alpha
    transparency, saving a new PNG.

.DESCRIPTION
    No image-editing tool or library is available on this machine, so this uses
    .NET's built-in System.Drawing (present in Windows PowerShell) to chroma-key
    pixel-by-pixel in HSV space: a pixel counts as background when its hue is
    close to the magenta/pink family (~336 degrees, measured from the actual
    generated backdrop, not assumed pure #FF00FF) and its saturation is high
    enough to rule out white/near-gray subject pixels. This also naturally
    catches a soft in-image drop shadow, since it shares the same hue, just at
    lower value. Edge pixels get a soft partial alpha (blended from hue/
    saturation "closeness" to the background) instead of a hard cutoff, to
    avoid jagged edges.

.EXAMPLE
    .\tools\Remove-MagentaBackground.ps1 -InFile "generated/furniture-test-bed2.png" -OutFile "assets/images/my-world/furniture/furniture-sparkly-bed.png"
#>
param(
    [Parameter(Mandatory = $true)]
    [string]$InFile,

    [Parameter(Mandatory = $true)]
    [string]$OutFile,

    # Hue of the actual generated backdrop, in degrees. Cloudflare's
    # flux-1-schnell renders "magenta" closer to hot pink (roughly 335-350
    # degrees, not pure #FF00FF's 300), and drifts a few degrees between
    # generations — so by default this is auto-sampled from the image's own
    # top-left corner pixel rather than assumed fixed. Pass a value explicitly
    # only to override.
    [double]$BackgroundHue = 0
)

$ErrorActionPreference = "Stop"
Add-Type -AssemblyName System.Drawing

function Get-ProjectRoot {
    Split-Path -Parent $PSScriptRoot
}

function Resolve-ProjectPath {
    param([string]$Path)
    if ([System.IO.Path]::IsPathRooted($Path)) { return $Path }
    return Join-Path (Get-ProjectRoot) $Path
}

function Get-Hsv {
    param([System.Drawing.Color]$Color)
    $r = $Color.R / 255.0
    $g = $Color.G / 255.0
    $b = $Color.B / 255.0
    $max = [Math]::Max($r, [Math]::Max($g, $b))
    $min = [Math]::Min($r, [Math]::Min($g, $b))
    $delta = $max - $min

    if ($delta -eq 0) { $h = 0 }
    elseif ($max -eq $r) { $h = 60 * ((($g - $b) / $delta) % 6) }
    elseif ($max -eq $g) { $h = 60 * ((($b - $r) / $delta) + 2) }
    else { $h = 60 * ((($r - $g) / $delta) + 4) }
    if ($h -lt 0) { $h += 360 }

    $s = if ($max -eq 0) { 0 } else { $delta / $max }
    return , @($h, $s)
}

function Clamp01 {
    param([double]$Value)
    if ($Value -lt 0) { return 0.0 }
    if ($Value -gt 1) { return 1.0 }
    return $Value
}

$resolvedIn = Resolve-ProjectPath -Path $InFile
$resolvedOut = Resolve-ProjectPath -Path $OutFile

$outDir = Split-Path -Parent $resolvedOut
if (-not (Test-Path $outDir)) {
    New-Item -ItemType Directory -Force -Path $outDir | Out-Null
}

$src = [System.Drawing.Bitmap]::FromFile($resolvedIn)
$w = $src.Width
$h = $src.Height
$dst = New-Object System.Drawing.Bitmap($w, $h, [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)

if ($BackgroundHue -eq 0) {
    $cornerHsv = Get-Hsv -Color $src.GetPixel(2, 2)
    $BackgroundHue = $cornerHsv[0]
    Write-Host "Auto-detected background hue: $([math]::Round($BackgroundHue, 1)) degrees"
}

$hueCoreTol = 20.0
$hueFeatherTol = 35.0
$satCore = 0.25
$satFeather = 0.12

for ($y = 0; $y -lt $h; $y++) {
    for ($x = 0; $x -lt $w; $x++) {
        $p = $src.GetPixel($x, $y)
        $hs = Get-Hsv -Color $p
        $hue = $hs[0]
        $sat = $hs[1]

        $hueDist = [Math]::Abs($hue - $BackgroundHue)
        if ($hueDist -gt 180) { $hueDist = 360 - $hueDist }

        $hueScore = Clamp01 (($hueFeatherTol - $hueDist) / ($hueFeatherTol - $hueCoreTol))
        $satScore = Clamp01 (($sat - $satFeather) / ($satCore - $satFeather))
        $magentaScore = [Math]::Min($hueScore, $satScore)

        $alpha = [int](255 * (1.0 - $magentaScore))
        $dst.SetPixel($x, $y, [System.Drawing.Color]::FromArgb($alpha, $p.R, $p.G, $p.B))
    }
}

$src.Dispose()
$dst.Save($resolvedOut, [System.Drawing.Imaging.ImageFormat]::Png)
$dst.Dispose()

Write-Host "Saved transparent PNG to: $resolvedOut"
